services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    volumes:
      - ./backend:/app
      - /app/node_modules # Use an anonymous volume to prevent host node_modules from overwriting container's
    depends_on:
      - mongo
    # Pass environment variables from a .env file in your backend directory
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/advdeception
    command: npm run dev
    ports:
      - "5000:5000"
    networks:
      - advdeception-net

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules # Use an anonymous volume to prevent host node_modules from overwriting container's
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true # Necessary for hot-reloading to work inside Docker
    ports:
      - "3000:3000"
    networks:
      - advdeception-net
  
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    command: mongod --wiredTigerCacheSizeGB 1 --bind_ip_all
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./mongo/data:/data/db
    networks:
      - advdeception-net

# no named volumes needed if you bind-mount host folders

networks:
  advdeception-net:
    external: true
