services:
  ssh-honeypot:
    build:
      context: ./honeypot
      dockerfile: Dockerfile
    container_name: ssh-honeypot
    ports:
      - "2222:22"
    volumes:
      - ./data/ttylogs:/var/log/tty
    restart: always
    networks:
      - advdeception-net

  ssh-parser:
    build:
      context: ./parser
      dockerfile: Dockerfile
    container_name: ssh-parser
    depends_on:
      - ssh-honeypot
    volumes:
      - ./data/ttylogs:/data/ssh_sessions
      - ./data/rawlogs:/data/raw
      - ./data/jsonlogs:/data/json
    environment:
      - MONGO_URI=mongodb://mongo:27017/advdeception
      - HONEYPOT_NAME=ssh-honeypot
      - SCAN_INTERVAL=10
    restart: always
    networks:
      - advdeception-net

networks:
  advdeception-net:
    external: true
